version: "3.7"
services:
  nexus:
    image: gd.clic/nexus:20191127
    user: root
    ports:
      - '18010:8081'
      - '18011:18011'
    volumes:
      - /var/nexus-data:/nexus-data
    logging:
      driver: "json-file"
      options: 
        max-size: "10m"
        max-file: "10"   
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      resources: 
        limits:
          cpus: '4.00'
          memory: 8.00G
        reservations:
          cpus: '2.00'
          memory: 2.00G
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 5s
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
  nexusproxy:
    image: gd.clic/nexusproxy:20191127
    depends_on:
      - nexus
    ports:
      - '18012:443'  # 443 -> 127.0.0.1:18011
    logging:
      driver: "json-file"
      options: 
        max-size: "10m"
        max-file: "5"         
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      resources: 
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.30'
          memory: 300M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 5s
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
