# 20191128
version: "3.7"
services:
  master:
    image: 10.20.145.10:18012/gd.clic/jenkins:20191128
    user: root
    ports:
      - 18013:8080
    volumes:
      - /var/jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options: 
        max-size: "5m"
        max-file: "5"  
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      resources: 
        limits:
          cpus: '4.00'
          memory: 8.00G
        reservations:
          cpus: '2.00'
          memory: 2.00G
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 5s
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first